const LOGIN_BEGIN = "LOGIN_BEGIN";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FIALURE = "LOGIN_FIALURE";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

const FETCH_STORE_BEGIN = "FETCH_STORE_BEGIN";
const FETCH_STORE_SUCCESS = "FETCH_STORE_SUCCESS";
const FETCH_STORE_FAILURE = "FETCH_STORE_FAILURE";
const FETCH_SPECIFIC_STORE = "FETCH_SPECIFIC_STORE";

const FETCH_PRODUCT_LIST_BEGIN = "FETCH_PRODUCT_LIST_BEGIN";
const FETCH_PRODUCT_LIST_SUCCESS = "FETCH_PRODUCT_LIST_SUCCESS";
const FETCH_PRODUCT_LIST_FAILURE = "FETCH_PRODUCT_LIST_BEGIN";

const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE";

const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

const ADD_PRODUCT_CART = "ADD_PRODUCT_CART";
const ADD_PRODUCT_QUANTITY = "ADD_PRODUCT_QUANTITY";
const SUB_PRODUCT_QUANTITY = "SUB_PRODUCT_QUANTITY";
const REMOVE_PRODUCT = "REMOVE_PRODUCT";

const PLACE_ORDER_BEGIN = "PLACE_ORDER_BEGIN";
const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
const PLACE_ORDER_FAILURE = "PLACE_ORDER_FAILURE";
const ORDER_PLACED = "ORDER_PLACED";
const FETCH_ORDER_LIST = "FETCH_ORDER_LIST";
const FETCH_SPECIFIC_ORDER = "FETCH_SPECIFIC_ORDER";

const GET_OTP_BEGIN = "GET_OTP_BEGIN";
const GET_OTP_SUCCESS = "GET_OTP_SUCCESS";
const GET_OTP_FAIL = "GET_OTP_FAIL";
const VERIFY_OTP = "VERIFY_OTP";

const UPLOAD_PRESCRIPTION = "UPLOAD_PRESCRIPTION";
const POST_PRESCRIPTION = "POST_PRESCRIPTION";

const STORE_SEARCH_BEGIN = "STORE_SEARCH_BEGIN";
const STORE_SEARCH_SUCCESS = "STORE_SEARCH_SUCCESS";
const STORE_SEARCH_FAIL = "STORE_SEARCH_FAIL";
const CLEAR_STORE_SEARCH = "CLEAR_STORE_SEARCH";
const PRODUCT_SEARCH_SUCCESS = "PRODUCT_SEARCH_SUCCESS";

const FETCH_STORE_ADDRESS_BEGIN = "FETCH_STORE_ADDRESS_BEGIN";
const FETCH_STORE_ADDRESS_SUCCESS = "FETCH_STORE_ADDRESS_SUCCESS";
const FETCH_STORE_ADDRESS_FAIL = "FETCH_STORE_ADDRESS_FAIL";
const FETCH_BULK_STORE_ADDRESS_SUCCESS = "FETCH_BULK_STORE_ADDRESS_SUCCESS";

const CLEAR_ERROR = "CLEAR_ERROR";

const ADD_USER_ADDRESS = "ADD_USER_ADDRESS";
const FETCH_USER_ADDRESS_LIST = "FETCH_USER_ADDRESS_LIST";

const ADD_TO_WISHLIST_BEGIN = "ADD_TO_WISHLIST_BEGIN";
const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";
const ADD_TO_WISHLIST_FAIL = "ADD_TO_WISHLIST_FAIL";
const FETCH_WISHLIST_SUCCESS = "FETCH_WISHLIST_SUCCESS";

const FETCH_BANNER = "FETCH_BANNER";

export {
  LOGIN_BEGIN,
  LOGIN_SUCCESS,
  LOGIN_FIALURE,
  FETCH_STORE_BEGIN,
  FETCH_STORE_SUCCESS,
  FETCH_STORE_FAILURE,
  FETCH_PRODUCT_LIST_BEGIN,
  FETCH_PRODUCT_LIST_SUCCESS,
  FETCH_PRODUCT_LIST_FAILURE,
  FETCH_CATEGORY_SUCCESS,
  FETCH_CATEGORY_FAILURE,
  REGISTER_USER_BEGIN,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_FAILURE,
  ADD_PRODUCT_CART,
  ADD_PRODUCT_QUANTITY,
  SUB_PRODUCT_QUANTITY,
  LOGOUT_SUCCESS,
  PLACE_ORDER_BEGIN,
  PLACE_ORDER_SUCCESS,
  PLACE_ORDER_FAILURE,
  ORDER_PLACED,
  FETCH_ORDER_LIST,
  GET_OTP_BEGIN,
  GET_OTP_SUCCESS,
  GET_OTP_FAIL,
  VERIFY_OTP,
  FETCH_SPECIFIC_ORDER,
  UPLOAD_PRESCRIPTION,
  POST_PRESCRIPTION,
  FETCH_SPECIFIC_STORE,
  REMOVE_PRODUCT,
  STORE_SEARCH_BEGIN,
  STORE_SEARCH_SUCCESS,
  STORE_SEARCH_FAIL,
  CLEAR_STORE_SEARCH,
  PRODUCT_SEARCH_SUCCESS,
  FETCH_STORE_ADDRESS_BEGIN,
  FETCH_STORE_ADDRESS_SUCCESS,
  FETCH_STORE_ADDRESS_FAIL,
  FETCH_BULK_STORE_ADDRESS_SUCCESS,
  CLEAR_ERROR,
  ADD_USER_ADDRESS,
  FETCH_USER_ADDRESS_LIST,
  ADD_TO_WISHLIST_BEGIN,
  ADD_TO_WISHLIST_SUCCESS,
  ADD_TO_WISHLIST_FAIL,
  FETCH_WISHLIST_SUCCESS,
  FETCH_BANNER,
};
